### ISSUE TITLE
the program wont remove the upgrade button

### ISSUE THREAD

**Issue by ghost** [Kibakus/SpotifyBlockNewUI#1]
the line of code inside xpss.js is changed so you need to update the line with .replace() method to
`.replace("&&a().createElement(hu,{onClick:C,className:yu.Z.UpgradeButton})", "")`

i have a suggestion for your phyton code, find this "().createElement(hu,{onClick:C,className:yu.Z.UpgradeButton})" string and with some string or regex function to remove any 3 characters behind that string, so you don't need to update your phyton code every time xpss.js is changed just by a little.

thank you.

**Comment by Mylloon** [comment]
Thanks, I made a PR (#2) and in case the maintainer doesn't want my work, there is my fork if you want it

**Comment by Kibakus** [comment]
Hi @Azternaut , at the beginning I thought that it would be just a frivolous project and did not think to update it further, but apparently people are using it and it will be necessary to make the code more adequate and practical. I will release an update today :)

**Comment by Kibakus** [comment]
https://github.com/Kibakus/SpotifyBlockNewUI/releases/tag/1.0.1

**Comment by ghost** [comment]
this project is very useful, as we know it because spotify frequently pushes an app update, thanks for updating the code!
