### ISSUE TITLE
upgrade button no longer removed from latest version 

### ISSUE THREAD

**Issue by subby2006** [Kibakus/SpotifyBlockNewUI#3]
Hello. I updated my Spotify to the latest version (version 1.1.60.672.g6ad9c215-a) and while your script removed the ad placeholder on the bottom, it couldn’t get rid of the upgrade button. Could you update the code so it can get rid of that? Thanks

**Comment by Kibakus** [comment]
Hello @subby2006
Hmm, I also have version 1.1.60.672.g6ad9c215-a, but the script works well. Throw me your xpui.spa and xpui.bak
%AppData%\Spotify\Apps\xpui.spa
%AppData%\Spotify\Apps\xpui.bak

Maybe someone has the same problem? Post off in the topic.

**Comment by Zephyr-1412** [comment]
i also have the same problem after running the "spotify.exe" nothing happens, neither the ad placeholder or the Spotify upgrade goes away. i am also on the same "version 1.1.60.672.g6ad9c215-a" also i am getting ads with this version but not with the original BTS version . Any help?

**Comment by Kibakus** [comment]
@Zephyr-1412 
https://dropmefiles.com/
Throw me your xpui.spa and xpui.bak
%AppData%\Spotify\Apps\xpui.spa
%AppData%\Spotify\Apps\xpui.bak

**Comment by Zephyr-1412** [comment]
https://dropmefiles.com/gvJjC

i dont have the xpui.bak but only the xpui.spa

**Comment by Kibakus** [comment]
@Zephyr-1412 
You have downloaded the latest version?
https://www.youtube.com/watch?v=5PekxCvEl3c

**Comment by Zephyr-1412** [comment]
yeah, it is working also I am getting ads is that intended. Also, is it possible for it to be working with Spicetify? https://github.com/JulienMaille/spicetify-dynamic-theme

**Comment by Kibakus** [comment]
@Zephyr-1412
Maybe someday
